baseurl = "/"
languageCode = "en"
googleAnalytics = "UA-123-45"
buildDrafts = true
title = "Camille Rabatel"
newContentEditor = "atom"

[blackfriday]
  extensions = ["hardLineBreak"]

[params]
  formSpreeEmail = "camille@raba.tel"
  description = "Camille Rabatel's personal website about photography"
  author = "Camille Rabatel"

[taxonomies]
  tag = "tags"

[permalinks]
  article = "/:section/:slug"
  gallery = "/:sections/:slug"
