---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/pages/article
  label: Articles
  create: all
  match: "**/*"
- type: directory
  path: src/pages/gallery
  label: Galleries
  create: all
  match: "**/*"
upload_dir: src/media
public_path: "/src/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
